import fs from 'node:fs';
import path from 'node:path';
import { NextResponse } from 'next/server';
import { MEDIA_DIR } from '../../../lib/paths';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';



const TYPES: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
};

/**
 * Serves CMS uploads. A route handler rather than public/ because the
 * production server snapshots public/ at build time — runtime uploads
 * would 404. Filenames are UUID-based and generated by us; anything that
 * does not look like one is refused before touching the filesystem.
 */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ name: string }> },
): Promise<NextResponse> {
  const { name } = await params;
  if (!/^[a-z0-9-]+\.(png|jpe?g|gif|webp)$/i.test(name)) {
    return new NextResponse(null, { status: 400 });
  }
  const file = path.join(MEDIA_DIR, name);
  if (!fs.existsSync(file)) return new NextResponse(null, { status: 404 });
  const ext = path.extname(name).toLowerCase();
  return new NextResponse(new Uint8Array(fs.readFileSync(file)), {
    headers: {
      'content-type': TYPES[ext] ?? 'application/octet-stream',
      // Uploads are immutable — a replaced image gets a new UUID name.
      'cache-control': 'public, max-age=31536000, immutable',
    },
  });
}
